
spring:
  application:
    name: eureka-consumer # Spring 应用名
server:
  port: 18710 # 服务器端口。默认为 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
